const jobData = [
    {
      "id": "0",
      "name": "Microsoft",
      "author": "microsoft@company.com",
      "date": "06-24-2022",
      "salary": "3000 USD",
      "fulltime": "false",
      "city": "London",
      "zipcode": "80000",
      "country": "United Kingdom",
      "title": "Engineer in Machine Learning",
      "content": "As an Engineer in Machine Learning, you will play a crucial role in developing and implementing machine learning models and algorithms to solve complex problems. Your primary responsibility will be to design, build, and optimize machine learning systems that can analyze and extract insights from large datasets Responsibilities:  Collaborate with cross-functional teams to understand business requirements and translate them into machine learning solutions. Develop and train machine learning models using various techniques such as deep learning, natural language processing, and statistical modeling. Conduct data preprocessing, feature engineering, and model evaluation to ensure high-quality and accurate results. Optimize and fine-tune models for performance, scalability, and efficiency. Work with software engineers to integrate machine learning models into production systems and ensure their smooth deployment. Stay up to date with the latest advancements in machine learning techniques, tools, and frameworks. Qualifications:  Bachelor's or Master's degree in Computer Science, Engineering, or a related field. Strong knowledge and practical experience in machine learning algorithms, statistical modeling, and data analysis. Proficiency in programming languages such as Python, R, or Java. Experience with machine learning libraries and frameworks (e.g., TensorFlow, PyTorch, scikit-learn). Familiarity with data manipulation and visualization tools (e.g., pandas, matplotlib). Solid understanding of software development principles and best practices. Excellent problem-solving skills and the ability to work on challenging and complex projects. Strong communication and collaboration skills to work effectively in a team environment. If you are passionate about leveraging machine learning to drive innovation, solve real-world problems, and contribute to cutting-edge projects, this role offers an exciting opportunity to apply your skills and make a significant impact in the field of artificial intelligence and data science. .",
      "logo": "https://cours-informatique-gratuit.fr/wp-content/uploads/2014/05/microsoft.png"
    },
    { "id": "1",
      "name": "Apple",
      "author": "apple@company.com",
      "date": "05-24-2022",
      "salary": "5000 USD",
      "fulltime": "false",
      "city": "Bristol",
      "zipcode": "81000",
      "country": "United Kingdom",
      "title": "UX / UI Designer",
      "content": "As a UI/UX designer, your primary responsibility is to create intuitive and visually appealing user interfaces for digital products. You will play a crucial role in enhancing the user experience and ensuring the usability of our applications.  Key Responsibilities:  Collaborate with cross-functional teams, including product managers, developers, and stakeholders, to understand user requirements and project goals. Conduct user research, including user interviews, surveys, and usability testing, to gather insights and identify user needs and pain points. Create wireframes, prototypes, and design mockups to visualize and communicate design ideas and solutions. Design user interfaces that are aesthetically pleasing, user-friendly, and aligned with the overall product branding and style guidelines. Develop and maintain design systems and guidelines to ensure consistency across different platforms and products. Conduct usability evaluations and iterate on designs based on user feedback and data analysis. Stay up to date with the latest industry trends, design tools, and best practices to continuously improve the quality of our designs. Qualifications:  Strong portfolio showcasing your UI/UX design skills and projects. Proficiency in design and prototyping tools such as Sketch, Adobe XD, Figma, or similar. Solid understanding of user-centered design principles and best practices. Ability to empathize with users and advocate for their needs throughout the design process. Knowledge of front-end development technologies (HTML, CSS, JavaScript) is a plus. Excellent communication and collaboration skills to work effectively in a team environment. Attention to detail and ability to balance multiple projects and deadlines. Problem-solving mindset and a passion for creating exceptional user experiences. Join our team as a UI/UX designer and contribute to creating innovative and delightful digital experiences for our users. Your creativity, attention to detail, and user-centric approach will be instrumental in shaping the future of our products.",
      "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Apple_Computer_Logo_rainbow.svg/1757px-Apple_Computer_Logo_rainbow.svg.png"
    },
    {
      "id": "2",
      "name": "Intel",
      "author": "intel@company.com",
      "date": "04-24-2022",
      "salary": "20000 USD",
      "fulltime": "true",
      "city": "Tokyo",
      "zipcode": "82000",
      "country": "Japan",
      "title": "Web Developer (FullStack)",
      "content": "As a Web Developer, your role will involve designing, building, and maintaining websites and web applications. You will be responsible for implementing client-side and server-side web development technologies to create functional and visually appealing online experiences. Your expertise in coding languages, frameworks, and tools will be essential in delivering high-quality websites that meet clients' requirements and align with industry best practices.  Responsibilities:  Collaborate with clients, designers, and stakeholders to understand project requirements and translate them into technical specifications. Develop responsive and user-friendly websites using HTML, CSS, and JavaScript. Utilize front-end frameworks such as React, Angular, or Vue.js to create interactive web applications. Implement back-end functionality using server-side languages like Python, PHP, or Node.js. Integrate databases and manage data through technologies like SQL or MongoDB. Optimize website performance, including page load speed and responsiveness, to enhance user experience. Conduct thorough testing and debugging to identify and resolve any issues or errors. Ensure cross-browser compatibility and adherence to web standards. Stay updated with the latest trends, technologies, and best practices in web development. Collaborate with the team to brainstorm ideas, share knowledge, and contribute to the improvement of development processes. Qualifications:  Proficiency in HTML, CSS, JavaScript, and related web technologies. Strong understanding of front-end frameworks, such as React, Angular, or Vue.js. Experience with server-side languages like Python, PHP, or Node.js. Familiarity with databases and query languages (e.g., SQL, MongoDB). Knowledge of version control systems (e.g., Git) for code management. Problem-solving skills to debug and troubleshoot technical issues. Attention to detail and ability to create visually appealing and user-friendly interfaces. Strong communication and collaboration skills to work effectively within a team. Adaptability to learn new technologies and frameworks as needed. Prior experience or projects demonstrating web development skills is a plus. Join our team as a Web Developer and contribute to the creation of innovative and impactful websites that drive businesses forward in the digital world.",
      "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Intel_logo_%282006-2020%29.svg/1005px-Intel_logo_%282006-2020%29.svg.png"
    },
    {
      "id": "3",
      "name": "Samsung",
      "author": "samsung@company.com",
      "date": "03-24-2022",
      "salary": "2000 USD",
      "fulltime": "false",
      "city": "Seoul",
      "zipcode": "83000",
      "country": "South Korea",
      "title": "Data Scientist",
      "content": "As a Data Scientist, you will be responsible for utilizing your expertise in data analysis, statistical modeling, and machine learning to extract meaningful insights from large and complex datasets. You will collaborate with cross-functional teams to identify business challenges, design data-driven solutions, and make data-driven recommendations to drive decision-making and business strategy.  Responsibilities:  Collect, clean, and preprocess large datasets from various sources. Perform exploratory data analysis to identify patterns, trends, and anomalies. Develop and implement statistical models and machine learning algorithms to solve complex business problems. Build predictive models and conduct statistical hypothesis testing to derive actionable insights. Collaborate with stakeholders to define project objectives and deliverables. Communicate findings and recommendations through data visualization and storytelling techniques. Stay updated with the latest advancements in data science, machine learning, and industry trends. Continuously improve data quality, accuracy, and model performance through iterative analysis and refinement. Qualifications:  Bachelor's degree in a quantitative field (e.g., Computer Science, Statistics, Mathematics) or a related discipline. Advanced degree (Master's or Ph.D.) is a plus. Strong analytical and problem-solving skills with a deep understanding of statistical concepts and modeling techniques. Proficiency in programming languages such as Python or R for data manipulation, analysis, and modeling. Experience with data visualization tools (e.g., Tableau, Matplotlib, ggplot) to effectively communicate insights. Familiarity with machine learning algorithms and frameworks (e.g., scikit-learn, TensorFlow, PyTorch). Solid understanding of databases, SQL, and data querying for data extraction and manipulation. Excellent communication skills to convey complex technical concepts to non-technical stakeholders. Strong attention to detail, ability to work independently, and meet project deadlines. Prior experience in data analysis, predictive modeling, or related fields is preferred. Join our team as a Data Scientist and contribute to driving data-informed decisions and unlocking valuable insights that will shape our business strategy and enhance customer experiences.",
      "logo": "https://www.samsung.com/etc.clientlibs/samsung/clientlibs/consumer/global/clientlib-common/resources/images/logo-square-letter.png"
    },
    {
      "id": "4",
      "name": "Ebay",
      "author": "ebay@company.com",
      "date": "02-24-2022",
      "salary": "5000 USD",
      "fulltime": "true",
      "city": "Shangai",
      "zipcode": "84000",
      "country": "China",
      "title": "Professional seller",
      "content": "As a Professional Seller, your main responsibility will be to drive sales and achieve revenue targets by effectively promoting and selling products or services to potential customers. You will play a crucial role in expanding our customer base and ensuring customer satisfaction. Your primary focus will be on building and maintaining relationships with clients, understanding their needs, and providing appropriate solutions.  Key Responsibilities:  Actively prospect and generate leads to identify potential customers and new business opportunities. Conduct market research to understand customer preferences, trends, and competitors' activities. Develop and implement effective sales strategies to achieve sales goals and targets. Present and demonstrate products or services to customers, highlighting their features and benefits. Build and maintain strong relationships with customers, addressing their inquiries, resolving issues, and providing after-sales support. Negotiate and close sales deals, ensuring favorable terms for both the customer and the company. Collaborate with cross-functional teams, such as marketing and product development, to provide feedback on customer needs and market trends. Stay updated with industry developments and continuously enhance product knowledge and selling skills. Qualifications and Skills:  Proven track record in sales, with a focus on achieving targets and driving results. Excellent communication and interpersonal skills to effectively engage and build relationships with customers. Strong negotiation and persuasion abilities to influence buying decisions. Ability to understand customer needs and provide appropriate solutions. Self-motivated and driven to succeed in a competitive sales environment. Good organizational and time management skills to prioritize tasks and meet deadlines. Proficiency in using sales tools, CRM systems, and technology for sales tracking and reporting. Flexibility to adapt to changing market conditions and customer requirements. Previous experience in a similar sales role or industry knowledge is a plus. Join our team as a Professional Seller and be part of a dynamic and rewarding sales environment where your contributions will directly impact the company's growth and success. We offer competitive compensation, professional development opportunities, and a supportive work culture.",
      "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCTlqMWPKsJ0kp6L_W7yI-p_5EvQYpTz43C4Ntu_QavehJb1sJhb66ALWZTB9nGwvMGL8&usqp=CAU"
    },
    {
      "id": "5",
      "name": "LVMH",
      "author": "lvmh@company.com",
      "date": "01-24-2022",
      "salary": "10000 USD",
      "fulltime": "true",
      "city": "Paris",
      "zipcode": "75000",
      "country": "France",
      "title": "Product engineer and designer",
      "content": "As a Product Engineer, you will play a vital role in the development and improvement of our company's products. You will work closely with cross-functional teams, including product managers, designers, and developers, to ensure the successful execution of product ideas and enhancements. Your primary responsibility will be to contribute to the design, development, testing, and implementation of new features and functionalities.  Key Responsibilities:  Collaborate with product managers and designers to understand product requirements and translate them into technical specifications. Participate in the entire product development lifecycle, from ideation and prototyping to implementation and deployment. Write clean and efficient code to build scalable and high-quality software components. Conduct thorough testing of product features to ensure they meet quality standards and user expectations. Identify and resolve technical issues and bugs in a timely manner. Continuously optimize and improve existing product features for better performance and user experience. Stay updated with the latest industry trends, technologies, and best practices related to product engineering. Skills and Qualifications:  Solid understanding of software development principles and methodologies. Proficiency in programming languages such as JavaScript, Python, or Java. Experience with front-end frameworks like React or Angular. Familiarity with back-end development and databases. Strong problem-solving skills and attention to detail. Effective communication and collaboration abilities. Ability to work in a fast-paced and dynamic environment, adapting to changing priorities and requirements. By joining our team as a Product Engineer, you will have the opportunity to contribute to innovative products and shape the user experience for our customers. Your technical expertise and passion for delivering high-quality software solutions will be instrumental in driving the success of our products.",
      "logo": "https://pbs.twimg.com/profile_images/918029450670772224/tj5dNzl2_400x400.jpg"
    },
    {
      "id": "6",
      "name": "Altrad",
      "author": "altrad@company.com",
      "date": "01-10-2022",
      "salary": "9000 USD",
      "fulltime": "false",
      "city": "Paris",
      "zipcode": "75100",
      "country": "France",
      "title": "Public works engineer",
      "content": "As a Public Works Engineer, your primary responsibility will be to oversee and manage various infrastructure projects within the public works sector. You will work closely with a team of engineers and professionals to design, develop, and implement infrastructure systems that contribute to the betterment of the community. Your expertise and technical knowledge will be essential in ensuring the successful execution of projects and adherence to regulatory standards.  Key Responsibilities:  Project Management: Coordinate and manage infrastructure projects, including planning, design, and construction phases. Monitor project timelines, budgets, and resources to ensure timely and efficient project completion. Design and Engineering: Develop engineering designs, drawings, and specifications for infrastructure projects, such as roads, bridges, water supply systems, wastewater treatment plants, and stormwater management systems. Ensure compliance with applicable codes and regulations. Permitting and Compliance: Assist in obtaining necessary permits and approvals from regulatory agencies. Ensure project compliance with environmental, safety, and zoning regulations. Quality Control: Conduct inspections and oversee quality control procedures to ensure the integrity and safety of infrastructure projects. Address any design or construction issues promptly and efficiently. Stakeholder Collaboration: Collaborate with government officials, contractors, consultants, and community stakeholders to address concerns, provide technical expertise, and ensure effective communication throughout project lifecycles. Budgeting and Cost Estimation: Prepare cost estimates, budgets, and project proposals. Monitor project expenditures and implement cost-saving measures where possible. Documentation and Reporting: Maintain accurate project documentation, including drawings, reports, and correspondence. Prepare progress reports and presentations for internal and external stakeholders. Requirements:  Bachelor's degree in Civil Engineering or a related field. Professional Engineer (PE) licensure preferred. Solid understanding of engineering principles, construction practices, and project management. Proficient in engineering software and design tools (e.g., AutoCAD, Civil 3D). Strong analytical and problem-solving skills. Excellent communication and interpersonal skills to collaborate with diverse stakeholders. Ability to work effectively in a team environment and manage multiple projects simultaneously. Knowledge of relevant regulations and codes governing public works projects. Join our team as a Public Works Engineer and contribute to the development and enhancement of essential infrastructure that serves our community's needs. You will have the opportunity to make a lasting impact by improving transportation systems, ensuring safe water supply, and promoting sustainable development.",
      "logo": "https://upload.wikimedia.org/wikipedia/fr/thumb/3/34/Logo_Groupe_Altrad.svg/1200px-Logo_Groupe_Altrad.svg.png"
    },
    {
      "id": "7",
      "name": "Orange",
      "author": "orange@company.com",
      "date": "06-24-2022",
      "salary": "3000 USD",
      "fulltime": "false",
      "city": "New York",
      "zipcode": "89000",
      "country": "United States of America",
      "title": "Telecom Engineer",
      "content": "As a Telecom Engineer, you will be responsible for designing, implementing, and maintaining telecommunication systems and networks. Your role will involve working with various technologies and equipment to ensure reliable and efficient communication services. Here are some key responsibilities and qualifications for the Telecom Engineer position:  Responsibilities:  Designing and configuring telecommunication systems, including networks, equipment, and infrastructure. Installing, testing, and maintaining telecommunications hardware and software components. Troubleshooting and resolving issues related to telecommunication systems and network connectivity. Conducting regular performance monitoring and optimization of telecommunication systems. Collaborating with cross-functional teams to integrate telecommunication systems with other IT infrastructure. Implementing security measures to protect telecommunication networks and data. Qualifications:  Bachelor's degree in Telecommunications, Electrical Engineering, or a related field. Solid understanding of telecommunications principles, protocols, and technologies. Proficiency in configuring and troubleshooting telecommunication equipment and systems. Knowledge of network protocols, such as TCP/IP, VLAN, and MPLS. Familiarity with telecommunication standards and regulatory requirements. Strong analytical and problem-solving skills. Excellent communication and teamwork abilities. Join our team as a Telecom Engineer and contribute to the development and maintenance of cutting-edge telecommunication systems. You will have the opportunity to work in a dynamic environment, collaborate with talented professionals, and make a significant impact on our communication infrastructure.",
      "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Orange_logo.svg/2044px-Orange_logo.svg.png"
    },
    {
      "id": "8",
      "name": "Google",
      "author": "google@company.com",
      "date": "06-02-2022",
      "salary": "4000 USD",
      "fulltime": "true",
      "city": "San Francisco",
      "zipcode": "82300",
      "country": "United States of America",
      "title": "Software Engineer",
      "content": "As a Software Engineer, you will play a crucial role in designing, developing, and maintaining software applications. You will be responsible for analyzing user requirements, designing efficient and scalable software solutions, and writing clean, maintainable code. Your expertise will contribute to the development of innovative software products that meet the needs of our customers.  Key Responsibilities:  Collaborate with cross-functional teams to gather and analyze software requirements. Design and develop software solutions that align with project specifications and industry best practices. Write high-quality, efficient, and maintainable code in various programming languages. Conduct thorough testing and debugging of software applications to ensure proper functionality and performance. Participate in code reviews and provide constructive feedback to peers. Identify and resolve software defects and issues. Maintain and update documentation related to software development processes and procedures. Stay up-to-date with emerging technologies and industry trends, and actively contribute to the continuous improvement of software development practices. Requirements:  Bachelor's degree in Computer Science, Software Engineering, or a related field. Strong knowledge of programming languages such as Java, Python, C++, or JavaScript. Familiarity with software development methodologies and best practices. Experience with software development tools and frameworks. Solid understanding of data structures, algorithms, and software design principles. Excellent problem-solving and analytical skills. Strong communication and collaboration abilities. Ability to work effectively both independently and in a team environment. Willingness to learn and adapt to new technologies and programming languages. Note: The above description is a general overview and may vary depending on the specific company and job requirements.",
      "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/800px-Google_%22G%22_Logo.svg.png"
    },
    {
      "id": "9",
      "name": "Facebook",
      "author": "facebook@company.com",
      "date": "03-22-2022",
      "salary": "3000 USD",
      "fulltime": "false",
      "city": "San Francisco",
      "zipcode": "80000",
      "country": "United States of America",
      "title": "Web Developer (back-end)",
      "content": "As a web developer, your role would involve creating and maintaining websites and web applications. You would work closely with designers, project managers, and other team members to understand the requirements and translate them into functional and visually appealing websites.  Responsibilities:  Develop and implement responsive web pages using HTML, CSS, and JavaScript. Collaborate with designers to create user-friendly interfaces and optimize web design elements. Write clean, efficient, and maintainable code. Conduct thorough testing and debugging to ensure optimal performance and compatibility across different browsers and devices. Integrate back-end functionalities, such as databases and APIs, to enable dynamic website interactions. Stay updated with the latest web development trends and technologies to enhance the website's functionality and user experience. Troubleshoot and resolve any issues or bugs that arise during development or after the website's launch. Ensure the website meets accessibility and security standards. Qualifications:  Proficiency in HTML, CSS, JavaScript, and related web technologies. Familiarity with front-end frameworks and libraries, such as React or Angular. Knowledge of back-end technologies, such as Node.js or PHP, and databases like MySQL or MongoDB. Experience with version control systems, such as Git. Strong problem-solving and analytical skills. Attention to detail and ability to follow design specifications. Good communication and teamwork skills. Working as a web developer offers an exciting opportunity to contribute to the creation of modern and engaging websites. It requires a combination of technical skills, creativity, and a passion for delivering high-quality web experiences. As a web developer, you would be part of a dynamic team, collaborating on projects and continuously expanding your knowledge in the ever-evolving field of web development.",
      "logo": "https://cdn.pixabay.com/photo/2015/05/17/10/51/facebook-770688_1280.png"
    },
    {
      "id": "10",
      "name": "Twitter",
      "author": "twitter@company.com",
      "date": "12-30-2022",
      "salary": "8930 USD",
      "fulltime": "false",
      "city": "Moscou",
      "zipcode": "22000",
      "country": "Russia",
      "title": "Publication moderator",
      "content": "As a Public Moderator, your role will involve actively monitoring and moderating public discussions and online communities to ensure a safe and respectful environment for all participants. You will play a crucial role in maintaining the quality of interactions, enforcing community guidelines, and addressing any inappropriate behavior or content.  Responsibilities:  Monitor online discussions and user-generated content across various platforms. Enforce community guidelines and policies to promote a positive and inclusive environment. Respond to user reports and address inappropriate behavior or content promptly and effectively. Engage with community members, answer their questions, and provide guidance when needed. Foster a sense of community by promoting constructive discussions and encouraging respectful interactions. Collaborate with the moderation team to develop and refine community guidelines and policies. Stay updated on emerging trends, issues, and concerns within the online community space. Requirements:  Excellent communication skills, both written and verbal. Strong interpersonal skills and the ability to handle challenging situations with tact and diplomacy. Attention to detail and the ability to spot and address potential issues proactively. Familiarity with various online platforms, social media, and community management tools. Understanding of online community dynamics, trends, and best practices. Ability to work independently and efficiently in a fast-paced, dynamic environment. Flexibility to adapt to changing priorities and handle multiple tasks simultaneously. A passion for fostering positive online communities and promoting respectful dialogue. Note: The specific responsibilities and requirements may vary depending on the company and platform where the Public Moderator role is based.",
      "logo": "https://cdn-icons-png.flaticon.com/512/124/124021.png"
    },
    {
      "id": "11",
      "name": "Instagram",
      "author": "instagram@company.com",
      "date": "09-14-2022",
      "salary": "30000 USD",
      "fulltime": "true",
      "city": "Instambul",
      "zipcode": "12000",
      "country": "Turkey",
      "title": "Video game creator",
      "content": "As a video game creator, your role is to design and develop interactive and engaging video games. You will work collaboratively with a team of game designers, artists, programmers, and sound engineers to bring game concepts to life. Your responsibilities will include:  Game Design: You will contribute to the overall game design process, including creating game mechanics, rules, levels, and characters. You'll be involved in brainstorming and refining ideas to ensure the game is enjoyable and meets the target audience's expectations. Game Development: Using game development tools and programming languages, you will implement the game mechanics, features, and user interfaces. You'll be responsible for coding gameplay elements, artificial intelligence, physics, and multiplayer functionalities. Prototyping and Testing: You will create prototypes of game concepts and mechanics to test and iterate on their gameplay experience. You'll gather feedback from playtesters and make necessary adjustments to improve the game's fun factor, balance, and usability. Collaboration: Working closely with artists and designers, you will integrate graphics, animations, audio, and visual effects into the game. You'll collaborate to ensure the game's visual and audio elements align with the intended artistic direction and enhance the player's immersion. Problem Solving: Throughout the game development process, you'll encounter challenges and technical issues. Your problem-solving skills will be crucial in identifying and resolving bugs, optimizing performance, and ensuring the game runs smoothly across various platforms and devices. Quality Assurance: You'll participate in quality assurance activities to ensure the game's functionality, performance, and user experience meet high standards. This includes testing the game for bugs, glitches, and inconsistencies, as well as providing feedback to improve gameplay and overall quality. Qualifications:  Strong passion for video games and knowledge of various game genres and platforms. Proficiency in game development tools and programming languages such as Unity, C++, C#, or JavaScript. Creativity and ability to think critically to design innovative and captivating game experiences. Strong problem-solving skills and attention to detail. Good communication and teamwork skills to collaborate effectively with multidisciplinary teams. Prior experience or education in game development, computer science, or a related field is a plus. If you are enthusiastic about creating immersive and entertaining video games, have a solid understanding of game design principles, and enjoy working in a dynamic and collaborative environment, this role as a video game creator may be a great fit for you.",
      "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png"
    },
    {
      "id": "12",
      "name": "IKEA",
      "author": "ikea@company.com",
      "date": "01-22-2022",
      "salary": "3000 USD",
      "fulltime": "false",
      "city": "Marseille",
      "zipcode": "30200",
      "country": "France",
      "title": "Sales manager with 8 years XP",
      "content": "As a Sales Manager, you would be responsible for leading and managing a team of sales professionals to achieve sales targets and drive business growth. Your main focus would be on generating revenue by acquiring new customers and expanding business with existing clients. You would develop and implement effective sales strategies, identify new market opportunities, and build strong relationships with key stakeholders.  Your day-to-day activities would include overseeing the sales team, setting sales goals and targets, conducting sales meetings and training sessions, and monitoring sales performance. You would provide guidance and support to your team members, helping them improve their sales techniques, negotiating skills, and customer relationship management.  As a Sales Manager, you would also collaborate with other departments such as marketing, product development, and customer service to ensure a coordinated approach to achieving overall business objectives. You would analyze market trends, competitor activities, and customer feedback to make informed decisions and adjustments to the sales strategies.  In this role, strong leadership and communication skills are essential. You would inspire and motivate your team to meet and exceed sales targets, resolve conflicts, and foster a positive and collaborative work environment. You would also interact with clients, build long-term relationships, and address their needs and concerns.  Overall, being a Sales Manager requires a combination of strategic thinking, sales expertise, leadership abilities, and a passion for driving business growth. It offers an opportunity to contribute to the success of the company by effectively managing sales operations and achieving revenue goals.",
      "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Ikea_logo.svg/2560px-Ikea_logo.svg.png"
    },
    {
      "id": "13",
      "name": "Uber",
      "author": "uber@company.com",
      "date": "11-03-2022",
      "salary": "1000 USD",
      "fulltime": "true",
      "city": "Wuhan",
      "zipcode": "23940",
      "country": "China",
      "title": "Professional Bus Driver",
      "content": "As a bus driver, your primary responsibility is to safely transport passengers to their destinations. You will operate a bus along designated routes, following established schedules and traffic regulations. Your duties will include picking up and dropping off passengers at designated stops, ensuring their safety and comfort throughout the journey.  Key Responsibilities:  Safely operate a bus and adhere to traffic laws and regulations. Follow assigned routes and schedules to ensure timely transportation of passengers. Assist passengers with boarding and disembarking the bus, ensuring their safety. Collect fares and issue tickets as required. Provide courteous and helpful customer service, addressing passenger inquiries and concerns. Maintain a clean and well-presented bus interior, including regular cleaning and maintenance checks. Monitor and report any operational issues or incidents to the appropriate authorities. Adhere to company policies and procedures, including safety protocols and guidelines. Attend training sessions and meetings to stay updated on regulations and job-related knowledge. Qualifications and Skills:  Possession of a valid driver's license with appropriate endorsements for operating a bus. Excellent driving skills and a proven track record of safe and responsible driving. Good knowledge of local traffic regulations and routes. Strong communication and interpersonal skills to interact with passengers in a friendly and professional manner. Ability to handle challenging situations calmly and maintain composure. Physical fitness and stamina to handle the demands of operating a bus, including sitting for extended periods, bending, and lifting. Ability to work flexible hours, including early mornings, evenings, weekends, and holidays, as bus schedules may vary. Prior experience as a bus driver or in a similar driving role is preferred but not always required. Join our team of dedicated bus drivers and contribute to providing reliable and efficient transportation services to our community. Apply today and be part of a rewarding career as a bus driver!",
      "logo": "https://www.grapheine.com/wp-content/uploads/uber-logo.jpg"
    },
    {
      "id": "14",
      "name": "Nakamura",
      "author": "nakamura@company.com",
      "date": "03-26-2022",
      "salary": "3400 USD",
      "fulltime": "false",
      "city": "Sydney",
      "zipcode": "12344",
      "country": "Australia",
      "title": "Bike tester and seller",
      "content": "As a Bike Tester, your main responsibility will be to test and evaluate bicycles for performance, safety, and functionality. You will play a crucial role in ensuring that the bikes meet quality standards and provide an excellent riding experience to customers. This position requires a passion for cycling, attention to detail, and strong analytical skills.  Key Responsibilities:  Conduct thorough testing and inspection of bicycles to assess their performance, durability, and safety features. Ride bicycles under various conditions, such as different terrains and weather conditions, to evaluate their handling, stability, and comfort. Identify any defects or issues with the bikes and report them to the appropriate teams for further analysis and improvement. Collaborate with the product development team to provide feedback and insights on bike design, components, and overall functionality. Maintain accurate records and documentation of testing procedures, results, and observations. Stay updated on the latest trends, technologies, and advancements in the cycling industry to contribute to the continuous improvement of bike design and performance. Requirements:  Passion for cycling and in-depth knowledge of bicycles, components, and industry trends. Excellent riding skills and ability to handle various types of bikes. Strong attention to detail and ability to identify and document issues and defects. Analytical mindset and ability to interpret test results and provide constructive feedback. Effective communication skills to collaborate with cross-functional teams and convey testing findings. Physical fitness and endurance to ride bikes for extended periods and in challenging conditions. Flexibility and adaptability to work in a dynamic and fast-paced environment. Prior experience in bike testing or related fields is preferred but not mandatory. Join our team of Bike Testers and contribute to the development of high-quality bicycles that bring joy and excitement to cyclists worldwide.",
      "logo": "https://d1yjjnpx0p53s8.cloudfront.net/styles/logo-thumbnail/s3/062012/bike.png?itok=hDjX-Npj"
    }
];

export default jobData;